type DiagramNode = { id: string; label: string; role: string; state?: string };
type DiagramEdge = { from: string; to: string; label?: string };
export type DiagramData = { nodes: DiagramNode[]; edges: DiagramEdge[] };

const diagrams: Record<string, { nodes: DiagramNode[]; edges: DiagramEdge[] }> = {
  'cpu-saturation': { nodes: [{ id: 'traffic', label: 'Traffic / k6', role: 'traffic_generator' }, { id: 'lb', label: 'API load balancer', role: 'load_balancer' }, { id: 'api', label: 'API pool', role: 'service' }, { id: 'dependency', label: 'Dependency', role: 'dependency' }, { id: 'prom', label: 'Prometheus', role: 'metrics' }], edges: [{ from: 'traffic', to: 'lb' }, { from: 'lb', to: 'api' }, { from: 'api', to: 'dependency' }, { from: 'prom', to: 'api', label: 'scrapes' }] },
  'vertical-horizontal': { nodes: [{ id: 'traffic', label: 'Traffic / k6', role: 'traffic_generator' }, { id: 'lb', label: 'Load balancer', role: 'load_balancer' }, { id: 'api1', label: 'API #1', role: 'service' }, { id: 'api2', label: 'API #2', role: 'service' }, { id: 'dependency', label: 'Dependency', role: 'dependency' }], edges: [{ from: 'traffic', to: 'lb' }, { from: 'lb', to: 'api1' }, { from: 'lb', to: 'api2' }, { from: 'api1', to: 'dependency' }, { from: 'api2', to: 'dependency' }] },
  'dependency-bottleneck': { nodes: [{ id: 'traffic', label: 'Traffic / k6', role: 'traffic_generator' }, { id: 'api', label: 'API pool', role: 'service' }, { id: 'dependency', label: 'Slow dependency', role: 'dependency' }, { id: 'queue', label: 'Dependency queue', role: 'saturation' }], edges: [{ from: 'traffic', to: 'api' }, { from: 'api', to: 'dependency' }, { from: 'dependency', to: 'queue' }] },
  'connection-pool': { nodes: [{ id: 'traffic', label: 'Traffic / k6', role: 'traffic_generator' }, { id: 'api', label: 'API', role: 'service' }, { id: 'pool', label: 'Connection pool', role: 'resource' }, { id: 'dependency', label: 'Dependency', role: 'dependency' }], edges: [{ from: 'traffic', to: 'api' }, { from: 'api', to: 'pool' }, { from: 'pool', to: 'dependency' }] },
  'latency-slo': { nodes: [{ id: 'traffic', label: 'Traffic / k6', role: 'traffic_generator' }, { id: 'api', label: 'API', role: 'service' }, { id: 'dependency', label: 'Dependency', role: 'dependency' }, { id: 'slo', label: 'Latency SLO', role: 'objective' }], edges: [{ from: 'traffic', to: 'api' }, { from: 'api', to: 'dependency' }, { from: 'slo', to: 'api', label: 'measures' }] },
  'dns-failure': { nodes: [{ id: 'traffic', label: 'Traffic / k6', role: 'traffic_generator' }, { id: 'api', label: 'API', role: 'service' }, { id: 'dns', label: 'DNS', role: 'network' }, { id: 'dependency', label: 'Dependency', role: 'dependency' }], edges: [{ from: 'traffic', to: 'api' }, { from: 'api', to: 'dns' }, { from: 'dns', to: 'dependency' }] },
  'retry-storm': { nodes: [{ id: 'traffic', label: 'Traffic / k6', role: 'traffic_generator' }, { id: 'api', label: 'API + retries', role: 'service' }, { id: 'dependency', label: 'Failing dependency', role: 'dependency' }, { id: 'loop', label: 'Retry amplification', role: 'feedback' }], edges: [{ from: 'traffic', to: 'api' }, { from: 'api', to: 'dependency' }, { from: 'dependency', to: 'loop' }, { from: 'loop', to: 'api' }] },
  'memory-leak': { nodes: [{ id: 'traffic', label: 'Traffic / k6', role: 'traffic_generator' }, { id: 'api', label: 'API', role: 'service' }, { id: 'memory', label: 'Memory / heap', role: 'resource' }, { id: 'dependency', label: 'Dependency', role: 'dependency' }], edges: [{ from: 'traffic', to: 'api' }, { from: 'api', to: 'memory' }, { from: 'api', to: 'dependency' }] },
  'autoscaler-oscillation': { nodes: [{ id: 'traffic', label: 'Changing traffic', role: 'traffic_generator' }, { id: 'autoscaler', label: 'Scaling policy', role: 'controller' }, { id: 'api', label: 'API capacity', role: 'service' }, { id: 'dependency', label: 'Dependency', role: 'dependency' }], edges: [{ from: 'traffic', to: 'autoscaler' }, { from: 'autoscaler', to: 'api' }, { from: 'api', to: 'dependency' }, { from: 'api', to: 'autoscaler', label: 'signal' }] },
};

export function ResourceDiagram({ id, active, phase, diagram: backendDiagram }: { id: string; active: boolean; phase?: string; diagram?: DiagramData }) {
  const diagram = backendDiagram ?? diagrams[id] ?? diagrams['cpu-saturation'];
  const positions = diagram.nodes.map((node, index) => ({ ...node, state: active ? phase : 'idle', x: 24 + (index % 3) * 150, y: 20 + Math.floor(index / 3) * 92 }));
  const byID = new Map(positions.map(node => [node.id, node]));
  return <section className={`resource-diagram ${active ? 'active' : ''}`} aria-label={`Resource diagram for ${id}`}>
    <div className="diagram-heading"><h3>Resource topology</h3><span>{active ? 'Live runtime state' : 'Scenario model'}</span></div>
    <svg viewBox="0 0 490 220" role="img" aria-label="Exercise resource topology"><defs><marker id="arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0,0 L7,3.5 L0,7 z" fill="#9bab99" /></marker></defs>
      {diagram.edges.map(edge => { const from = byID.get(edge.from)!; const to = byID.get(edge.to)!; return <g key={`${edge.from}-${edge.to}`}><line className="diagram-edge" x1={from.x + 58} y1={from.y + 27} x2={to.x + 58} y2={to.y + 27} /><text className="diagram-edge-label" x={(from.x + to.x) / 2 + 58} y={(from.y + to.y) / 2 + 22}>{edge.label}</text></g>; })}
       {positions.map(node => <g key={node.id} className={`diagram-node node-${node.role} state-${node.state}`} transform={`translate(${node.x},${node.y})`}><rect width="116" height="54" rx="5" /><text x="58" y="22" textAnchor="middle">{node.label}</text><text className="node-role" x="58" y="39" textAnchor="middle">{node.state ?? node.role}</text></g>)}
    </svg>
  </section>;
}
